# Generated by Django 3.1.6 on 2021-02-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 2), ('vip', 1), ('default', 0)], default='default', max_length=10),
        ),
    ]
